# Source - https://stackoverflow.com/a/79598992
# Posted by thisismydesign
# Retrieved 2026-09-10, License - CC BY-SA 4.0

services:
  db:
    image: postgres:18-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    # from here: https://wiki.alpinelinux.org/wiki/Postgresql?__goaway_challenge=cookie&__goaway_id=907525f0bcbffeeba5f613162da596c4&__goaway_referer=https%3A%2F%2Fwww.google.com%2F
    run:
      - apk add postgresql18 postgresql18-contrib
      - rc-update add postgresql
      - rc-service postgresql start

