# from here: https://docs.github.com/en/actions/tutorials/use-containerized-services/create-postgresql-service-containers#running-jobs-in-containers
name: PostgreSQL service example
on: push

jobs:
  # Label of the container job
  container-job:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
    container: node:20-bookworm-slim

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:latest
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: TabBooks
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432


    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v6

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.6'

      - name: install packages
        run: |
          apt-get -y update
          apt-get install --yes --no-install-recommends postgresql-client
          apt-get install --yes r-cran-dbi unixodbc unixodbc-dev odbc-postgresql libcurl4-openssl-dev libpq-dev

      - name: Wait for PostgreSQL
        run: |
          until pg_isready -h localhost -p 5432; do
            echo 'waiting for postgres...'
            sleep 1
          done

      - name: run psql
        env:
          PGUSER: postgres
          PGPASSWORD: postgres
        run: |
          psql -h postgres -U postgres -f test-code.sql 
          psql -h postgres -U postgres -c 'SELECT * FROM public."Book";'
        working-directory: ./SQL

      - name: install r package 
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::odbc
            any::RPostgreSQL
            any::RPostgres
          needs: check

      - name: run R
        run: |
          Rscript -e 'odbc::odbcListDataSources() |> print()#conn <- DBI::dbConnect(odbc::odbc(), dsn = "TabBooks"); "SELECT * FROM public.\"Book\"" |> DBI::dbGetQuery(conn, statement = _)'
        env:
          PGUSER: postgres
          PGPASSWORD: postgres

      - name: run R 2
        run: |
          drv <- RPostgres::Postgres()
          con <- DBI::dbConnect(
            drv, 
            dbname = "TabBooks",
            port = 5432,
            host = "localhost",
            user = "postgres", 
            password = "postgres"
          )
          DBI::dbListTables(con)
          DBI::dbDisconnect(con)
        shell: Rscript {0}
